act_frames: 120 #Сколько кадров брать для распознавания поз и действий на их очнове
batch_size: 16 #Размер батча пакетной обработки кадров
multimodal_model: TST #название мультимодальной модели распознания действий (не реализовано)
pose_action_model: STGCN_model_kinetics # название модели распознания действий по позам (STGCN_model_rgbd, STGCN_model_kinetics, Conv3dNet, LSTMSkeletonNet)
pose_ext_model: YOLOv26-Pose-N # Название модели распознавания поз (YOLOv8-Pose-N, YOLOv8-Pose-S, YOLOv26-Pose-N)
video_decimation: 1 # степень прореживания кадров (может ускорить обработку, но уменьшить точность)
pose_ext_th: 0.3 # порог уверенности модели (распознания поз и распознания действий), ниже которого не принимать результат
min_pose_frames: 30 # минимальное число кадров с одним ID актера для запуска анализа действий
min_pair_poses_frames: 30 # минимальное число кадров с парой актеров (одновременно двух) с одними ID для запуска анализа действий
